Neste experimento, o sujeito está sentado a 60 cm de distância de um monitor, onde ele se concentra em um dos múltiplos alvos que piscam rapidamente, alternando entre as cores preto e branco. Para cada sujeito, existem dois arquivos representando duas sessões. Cada sessão possui dez tentativas de dezesseis segundos cada.

- Imprimir gráficos dos três dominios 
- Gerar o objeto mne.EpochsArray e plotar os gráficos (amostra), com os cortes de frequência (4-14 Hz) dos dados evocados
- Aplica o filtro passa-faixa sobre as frequências de interesse (Verificar qual a menor e a maior frequência evocada) **[PARA O DIA 18/09]**
- Classificação por isolamento de frequência

In [2]:
# imports

from scipy.io import loadmat
import numpy as np

In [4]:
# pré-carregamento

avi_data = list()
for i in range(1,6):
    # TODO CONCATENAR ESSAS LINHAS EM UM ARRAY SÓ
    avi_data.append(loadmat(f"../../../datasets/avi/multi/Sub{i}_1_multitarget.mat"))
    avi_data.append(loadmat(f"../../../datasets/avi/multi/Sub{i}_2_multitarget.mat"))
    

In [7]:
# extração direta dos dados

X = [d['Data'][0][0][7] for d in avi_data]
y = [d['Data'][0][0][8][0] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)
(8192, 10)

Divisão dos rótulos (sequências):
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]


In [8]:
# organização dos dados

# DEVE SIM
# NÃO DEVERIA JUNTAR A LINHA 0 COM A LINHA 1? ASSIM DIMINUINDO DE 10 PARA 5 LINHAS? VISTO QUE SÃO APENAS 5 PARTICIPANTES

reshape_X = np.array([np.transpose(data) for data in X])
print(reshape_X.shape)
reshape_X = reshape_X.reshape(reshape_X.shape[0]*reshape_X.shape[1], reshape_X.shape[2])
reshape_X.shape

reshape_Y = np.array([np.transpose(data) for data in y])
print(reshape_Y.shape)
reshape_Y = reshape_Y.reshape(1, reshape_Y.shape[0]*reshape_Y.shape[1])[0]
len(reshape_Y)

(10, 10, 8192)
(10, 10)


100

In [9]:
# salvar dados numpy

np.save("../../../datasets/avi/multi/data.npy", reshape_X)
np.save("../../../datasets/avi/multi/labels.npy", reshape_Y)